version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    build:
      context: ./docker
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app